<a href="https://colab.research.google.com/github/Edu-Fidelis/ProjetoDataScience/blob/main/Dia_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Importando bibliotecas e dados**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dados = pd.read_csv('sds_fifa.csv')

In [3]:
dados.head()

Unnamed: 0               Nome  ...  Salario Total_Pontos
0           0         J. Lingard  ...     €95K         2064
1           1   A. Bella-Kotchap  ...      €2K         1439
2           2          T. Souček  ...     €46K         2075
3           3    Felipe Anderson  ...     €50K         2008
4           4       A. Griezmann  ...    €270K         2276

[5 rows x 9 columns]

In [4]:
dados.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
dados.head()

Nome  Idade Posicao  ...               Time  Salario Total_Pontos
0         J. Lingard     27     CAM  ...  Manchester United     €95K         2064
1   A. Bella-Kotchap     18      CB  ...    VfL Bochum 1848      €2K         1439
2          T. Souček     25     CDM  ...    West Ham United     €46K         2075
3    Felipe Anderson     27      LM  ...           FC Porto     €50K         2008
4       A. Griezmann     29      ST  ...       FC Barcelona    €270K         2276

[5 rows x 8 columns]

#**Pré-processamento dos dados**

In [7]:
dados.columns

Index(['Nome', 'Idade', 'Posicao', 'Media', 'Potencial', 'Time', 'Salario',
       'Total_Pontos'],
      dtype='object')

In [8]:
colunas = ['Nome', 'Time']

In [9]:
dados.drop(colunas, axis=1, inplace=True)

In [10]:
dados = dados[['Idade', 'Posicao', 'Media', 'Potencial','Total_Pontos', 'Salario']]

In [11]:
dados.head()

Idade Posicao  Media  Potencial  Total_Pontos Salario
0     27     CAM     77         77          2064    €95K
1     18      CB     67         85          1439     €2K
2     25     CDM     81         86          2075    €46K
3     27      LM     80         80          2008    €50K
4     29      ST     86         86          2276   €270K

Separando os dados em duas partes: X que são os elementos previsores e Y que será nosso obejtivo (no caso definir os salários dos jogadores)

In [12]:
x = dados.iloc[ : , :-1].values

In [13]:
print(x)

[[27 'CAM' 77 77 2064]
 [18 'CB' 67 85 1439]
 [25 'CDM' 81 86 2075]
 ...
 [21 'CDM' 79 86 1823]
 [31 'ST' 92 92 2213]
 [20 'CAM' 81 91 1997]]


In [14]:
y = dados.iloc[ : , -1].values

In [15]:
print(y)

['€95K' '€2K' '€46K' ... '€31K' '€270K' '€95K']


Começando a criar nosso modelo de machine learning
Vamos transformar a coluna de posição em números (dumming arraybles) para a machine learning recebê-la

In [19]:
# Importando bibliotecas
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = ct.fit_transform(x).toarray()

In [20]:
print(x)

[[1.000e+00 0.000e+00 0.000e+00 ... 7.700e+01 7.700e+01 2.064e+03]
 [0.000e+00 1.000e+00 0.000e+00 ... 6.700e+01 8.500e+01 1.439e+03]
 [0.000e+00 0.000e+00 1.000e+00 ... 8.100e+01 8.600e+01 2.075e+03]
 ...
 [0.000e+00 0.000e+00 1.000e+00 ... 7.900e+01 8.600e+01 1.823e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 9.200e+01 9.200e+01 2.213e+03]
 [1.000e+00 0.000e+00 0.000e+00 ... 8.100e+01 9.100e+01 1.997e+03]]


#**Criando Machine Learning**

Vamos treinar/ensinar nossa Máquina

In [21]:
from sklearn.model_selection import  train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [22]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [23]:
regressor.fit(x_train, y_train)

ValueError: ignored

In [24]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

NotFittedError: ignored

In [ ]:
# Vendo a acurácia
regressor.score(x_test, y_test)

In [ ]:
importancia = regressor.coef_

In [ ]:
for i, v in enumerate(importancia):
  print('Feature: %0d, Score: %.5f' % (i, v))

plt.bar([ x for x in range(len(importancia))], importancia)
plt.show()

In [ ]:
# Criando gráficos para melhor visualização
sns.regplot(x='Potencial', y='Salario', data='dados')
sns.lmplot(x='Media', y='Salario', data=dados, x_estimator=np.mean)
sns.jointplot(x='Potencial', y='Salario', data='dados', kind='reg')
